### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by kyroskoh** [arghblargh/QueueBot#1]
HOST="irc.twitch.tv"
PORT=6667
NICK="Fruit_Bot"
PASS="oauth:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
IDENT="fruit"
REALNAME="LoserFruit's Queue Bot"
INIT_CHANNEL="#loserfruit"
ADMIN="KyrosKoh"
SAVE_FILE='data.xml'
MIN_DELAY=datetime.timedelta(0,2,500000) # 2.5 second delay between sent messages

---

When I have executed the script, the error occured:

-sh-4.1$ python QueueBot.py
Traceback (most recent call last):
  File "QueueBot.py", line 438, in <module>
    main()
  File "QueueBot.py", line 207, in main
    load_data()
  File "QueueBot.py", line 156, in load_data
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

---

Since In Python 3.3, IOError became an alias for OSError, and FileNotFoundError is a subclass of OSError. 

---

Line 156:

```
except FileNotFoundError:
    print("   > load_data: file not found")
```

---

Line 156:

I have changed to:         

except (OSError, IOError) as e:
                print("   > load_data: file not found")

---

Result:

-sh-4.1$ python QueueBot.py

> load_data: file not found
> :tmi.twitch.tv 001 fruit_bot :Welcome, GLHF!
> :tmi.twitch.tv 002 fruit_bot :Your host is tmi.twitch.tv
> :tmi.twitch.tv 003 fruit_bot :This server is rather new
> :tmi.twitch.tv 004 fruit_bot :-
> :tmi.twitch.tv 375 fruit_bot :-
> :tmi.twitch.tv 372 fruit_bot :You are in a maze of twisty passages, all alike.
> :tmi.twitch.tv 376 fruit_bot :>

---

Do you have your data.xml sample data? empty skeleton format?

**Comment by arghblargh** [comment]
If the .xml file doesn't exist, the bot will create one.
